---
name: Checks

on: [push]

jobs:
    test-lint:  # ID of the job which can be used
        name: Test and Lint
        runs-on: ubuntu-20.04
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ 'athulmathew.varughese@factweavers.com' }}
                password: ${{ 'Athul@dbiz' }}
            - name: Checkout
              uses: actions/checkout@v2
            - name: Test
              run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
            - name: Lint
              run: docker-compose run --rm app sh -c "flake8"
